### ISSUE TITLE
using pane borderless=true results in zellij crash

### ISSUE THREAD

**Issue by cosmikwolf** [dj95/zjstatus#20] opened 2023-11-04 07:52 UTC
When I use the following layout using kitty terminal, it seems like zellij is trying to add borders, but then the next render it removes it, and this locks up the zellij server and I get the error below 

```
layout {
  pane borderless=true
  pane size=1 borderless=true {
    plugin location="file:~/.local/share/zellij/zjstatus.wasm" {
            format_left  "{mode} #[fg=#89B4FA,bold]{session} {tabs}"
            format_right "{datetime}"
            format_space ""

            border_enabled  "true"
            border_char     "─"
            border_format   "#[fg=#6C7086]{char}"
            border_position "top"

            hide_frame_for_single_pane "true"

            mode_normal  "#[bg=blue] "
            mode_tmux    "#[bg=#ffc387] "

            tab_normal   "#[fg=#6C7086] {name} "
            tab_active   "#[fg=#9399B2,bold,italic] {name} "

            datetime        "#[fg=#6C7086,bold] {format} "
            datetime_format "%A, %d %b %Y %H:%M"
            datetime_timezone "Europe/Berlin"
        }
    }
}
```

```
Your zellij client lost connection to the zellij server.

As a safety measure, you have been disconnected from the current zellij session.
However, the session should still exist and none of your data should be lost.

This usually means that your terminal didn't process server messages quick
enough. Maybe your system is currently under high load, or your terminal
isn't performant enough.

There are a few things you can try now:
    - Reattach to your previous session and see if it works out better this
      time: `zellij attach lucky-piano`
    - Try using a faster (maybe GPU-accelerated) terminal emulator
```

Not sure if this is a zjstatus bug, or a zellij bug. I will submit to both repos.
https://github.com/zellij-org/zellij/issues/2901

**Comment by dj95** [comment] 2023-11-05 09:30
Hey,

I've tried to reproduce the issue, but it does not occur on my side. Testing it with your provided layout and the following versions:

- kitty `0.30.1`
- zellij `0.38.2` && `main`
- zjstatus `0.8.0`
- os `macOS 14.1`

Have you already tried to clean the cache? It's located at `~/.cache/zellij` under linux and `~/Library/Caches/org.Zellij-Contributors.Zellij/` under macOS.

**Comment by dj95** [comment] 2023-11-05 09:34
Have you also tried to set pane size for zjstatus to `2`? When you enable the border in zjstatus, the size must be at least `2`, since it otherwise won't render properly. This could also cause the issue.

**Comment by dj95** [comment] 2023-11-15 20:36
Hi @cosmikwolf 

Do you have any updates on this?

**Comment by dj95** [comment] 2023-12-14 06:17
Hello,

I kindly ask you, if the issue still persist and if you tried the solutions. Otherwise I'll close the issue, since it is not reproducible and I assume that it's working due to the missing feedback.

**Comment by ElPapiMango** [comment] 2023-12-26 17:07
Hi, I got the same issue when using his config. I updated pane size to 2 but same issue.

Windows Terminal Preview, Version: 1.19.3172.0
zellij 0.38.2
zjstatus 0.8.0

**Comment by dj95** [comment] 2023-12-26 17:22
Hi,

have you already tried the latest versions of zellij and zjstatus?

**Comment by dj95** [comment] 2023-12-26 17:47
<img width="1784" alt="Screenshot 2023-12-26 at 18 47 16" src="https://github.com/dj95/zjstatus/assets/4348959/855b0c8e-ea7d-424e-bd65-411e16f8b20d">

As mentioned before, I cannot reproduce it. Please try to give as many information as possible and try the latest version + clean the cache from zellij.

**Comment by ElPapiMango** [comment] 2023-12-26 18:01
Did you try to crate new pane once loaded? ALT+n?

**Comment by ElPapiMango** [comment] 2023-12-26 18:05
I downloaded zjstatus 0.11 and its same there.

**Comment by dj95** [comment] 2023-12-26 18:14
That produces glitchy visuals for me. It jumps back and forth with the pane borders, since zjstatus will not be able to detect whether pane borders are active or not. But it des not crash on my side.

Can you try to set `hide_frame_for_single_pane` to `false` and test it again, please?

**Comment by dj95** [comment] 2023-12-26 18:40
If you approve, that it works on your side, I could directly release the bugfix, @ElPapiMango .

Found an issue with the border calculation when the first pane is not able to retrieve a border. Thanks for the details! It really helped me!

<img width="1784" alt="Screenshot 2023-12-26 at 19 40 20" src="https://github.com/dj95/zjstatus/assets/4348959/262014eb-980f-49c8-9d3f-e9509769c0f1">

**Comment by ElPapiMango** [comment] 2023-12-26 18:54
> Can you try to set `hide_frame_for_single_pane` to `false` and test it again, please?

No issues when doing this.👍🏻

**Comment by dj95** [comment] 2023-12-26 19:05
Thanks a lot, @ElPapiMango ! Release 0.11.1 contains the fix.

**Closed by dj95** 2023-12-26 19:05 UTC
Labels: bug
